# Generated by Django 2.0.4 on 2018-04-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='subtitle',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
